Book.objects.all()
Librarian.objects.get(library="")
Book.objects.filter(name=author_name), books.all()
Library.objects.get(name=library_name), books.all()
Library.objects.get(name=librarian_name)
Author.objects.get(name=author_name), objects.filter(author=author)